# Generated by Django 2.1.2 on 2018-10-28 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=256)),
                ('weight', models.DecimalField(decimal_places=5, default=0, max_digits=14)),
                ('delivery_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_parcels', to='locations.Location')),
                ('departure_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_parcels', to='locations.Location')),
            ],
        ),
    ]
